---
# @see https://docs.influxdata.com/influxdb/v1.0/introduction/installation/
- yum:
    name: "{{ influxdb_download_path }}"
  sudo: true

- service:
    name: influxdb
    state: started
    enabled: true
  sudo: true

# create database if not exists.
- name: check whether database is already exists
  command: influx -database "{{ influxdb_dbname }}" -execute "select 1 from /influxdb.*/;"
  failed_when: false
  register: database_existance

- wait_for:
    port: 8086
    delay: 10

- command: influx -execute "create database {{ influxdb_dbname }}"
  when: database_existance.rc != 0
