---
# @see http://docs.grafana.org/installation/rpm/
- yum:
    name: "{{ grafana_download_path }}"
  sudo: true

- service:
    name: grafana-server
    state: started
    enabled: true
  failed_when: false
  sudo: true

- wait_for:
    port: 3000
    delay: 5
