---
- yum:
    name: "{{ telegraf_download_path }}"
  sudo: true

- template:
    src: telegraf.conf.j2
    dest: "/etc/telegraf/telegraf.conf"
    owner: telegraf
    group: telegraf
    backup: yes
  sudo: true

- service:
    name: telegraf
    state: started
  sudo: true
